target = ledramp
simavr-repo = ./simavr
simavr = ${simavr-repo}/simavr
simavr-parts = ${simavr-repo}/examples/parts

firm_src = ${wildcard ./src/at*.c}
firmware = ${firm_src:.c=.axf}

IPATH += ${simavr-parts}
IPATH += ${simavr}/sim
IPATH += ${simavr}/cores

VPATH = ./src
VPATH += ${simavr-repo}/examples/parts

SIMAVR-OBJ := obj-${shell $(CC) -dumpmachine}
OBJ-PREFIX := obj
OBJ := ${OBJ-PREFIX}/${SIMAVR-OBJ}


ifeq (${shell uname}, Darwin)
CFLAGS += -DGL_SILENCE_DEPRECATION
LDFLAGS += -L${simavr}/${SIMAVR-OBJ} -lsimavr
else
LDFLAGS += -L${simavr}/${SIMAVR-OBJ} -l:libsimavr.a
endif
LDFLAGS += -lpthread
LDFLAGS  += -lSDL2 -lsimavr -lm -lelf


CFLAGS  += -O2 -Wall -Wextra -Wno-unused-parameter
CFLAGS  += -Wno-unused-result -Wno-missing-field-initializers
CFLAGS  += -Wno-sign-compare
CFLAGS  += -g


CPPFLAGS += --std=gnu99 -Wall
CPPFLAGS += ${patsubst %,-I%,${subst :, ,${IPATH}}}


include ${simavr-repo}/examples/Makefile.opengl

all: ${OBJ} libsimavr ${firmware} ${target}

include ./Makefile.common

libsimavr:
	${E}echo BUILD $@; make -C ${simavr} libsimavr
	@echo $@ done

${OBJ}:
	${E}echo MKDIR $@; mkdir -p ${OBJ}

board = ${OBJ}/${target}.elf

${board} : ${OBJ}/button.o
${board} : ${OBJ}/${target}.o

${target}: ${board}
	${E}echo COPY $< to $@; cp ${board} $@
	@echo $@ done

clean:
	${E}echo CLEAN simavr; make -C ${simavr-repo} clean
	${E}echo RMDIR ${OBJ-PREFIX}; rm -r ${OBJ-PREFIX}
	@echo $@ done

.PHONY: all libsimavr clean

# include the dependency files generated by gcc, if any
-include ${wildcard ${OBJ}/*.d}
